version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-db
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--appendonly', 'yes']
  postgres:
    image: postgres:latest
    container_name: quiz-system-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: quiz-system
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
